# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CsvImporter
                                 A QGIS plugin
 This plugin imports a CSV file into your project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-27
        copyright            : (C) 2024 by m0squdev
        email                : valerio.mosqu@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CsvImporter class from file CsvImporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .csv_importer import CsvImporter
    return CsvImporter(iface)
